var num1 = 100;
var num2 = 200;
var res;
res = num1 + num2;
console.log("sum of two number is :" + res);
var res1 = num2 - num1;
console.log("result of substraction:" + res1);
var res12 = num2 * num1;
console.log("result of substraction:" + res12);
var res3 = num2 / num1;
console.log("result of substraction:" + res3);
